/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardRbacExplanationRouteImport } from './routes/dashboard/rbac-explanation'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAllTasksRouteImport } from './routes/dashboard/all-tasks'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as AuthVerify2faRouteImport } from './routes/auth/verify-2fa'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/notifications/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardSettingsWorkspaceRouteImport } from './routes/dashboard/settings/workspace'
import { Route as DashboardSettingsTemplatesRouteImport } from './routes/dashboard/settings/templates'
import { Route as DashboardSettingsTeamManagementRouteImport } from './routes/dashboard/settings/team-management'
import { Route as DashboardSettingsShortcutsRouteImport } from './routes/dashboard/settings/shortcuts'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsRolesUnifiedRouteImport } from './routes/dashboard/settings/roles-unified'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsLocalizationRouteImport } from './routes/dashboard/settings/localization'
import { Route as DashboardSettingsFiltersRouteImport } from './routes/dashboard/settings/filters'
import { Route as DashboardSettingsEmailRouteImport } from './routes/dashboard/settings/email'
import { Route as DashboardSettingsDataManagementRouteImport } from './routes/dashboard/settings/data-management'
import { Route as DashboardSettingsCalendarRouteImport } from './routes/dashboard/settings/calendar'
import { Route as DashboardSettingsAuditLogsRouteImport } from './routes/dashboard/settings/audit-logs'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings/appearance'
import { Route as DashboardSettingsApiRouteImport } from './routes/dashboard/settings/api'
import { Route as DashboardSettingsLayoutRouteImport } from './routes/dashboard/settings/_layout'
import { Route as DashboardProfileUserIdRouteImport } from './routes/dashboard/profile/$userId'
import { Route as DashboardAnalyticsScheduledRouteImport } from './routes/dashboard/analytics/scheduled'
import { Route as DashboardAnalyticsBuilderRouteImport } from './routes/dashboard/analytics/builder'
import { Route as DashboardAdminRolesRouteImport } from './routes/dashboard/admin/roles'
import { Route as DashboardWorkspaceSettingsWorkspaceIdIndexRouteImport } from './routes/dashboard/workspace-settings/$workspaceId/index'
import { Route as DashboardWorkspaceWorkspaceIdTemplatesRouteImport } from './routes/dashboard/workspace/$workspaceId/templates'
import { Route as DashboardTeamsWorkspaceIdLayoutRouteImport } from './routes/dashboard/teams/$workspaceId/_layout'
import { Route as DashboardSettingsRolesUnifiedRoleIdRouteImport } from './routes/dashboard/settings/roles-unified.$roleId'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId'
import { Route as DashboardTeamsWorkspaceIdLayoutRolesRouteImport } from './routes/dashboard/teams/$workspaceId/_layout.roles'
import { Route as DashboardTeamsWorkspaceIdLayoutMembersRouteImport } from './routes/dashboard/teams/$workspaceId/_layout.members'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/settings'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/notes'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/milestones'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/board'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/backlog'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/analytics'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout.index'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout.timeline'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout.teams'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout.list'
import { Route as DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRouteImport } from './routes/dashboard/workspace/$workspaceId/project/$projectId/_layout.calendar'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRbacExplanationRoute =
  DashboardRbacExplanationRouteImport.update({
    id: '/rbac-explanation',
    path: '/rbac-explanation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAllTasksRoute = DashboardAllTasksRouteImport.update({
  id: '/all-tasks',
  path: '/all-tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: '/auth/verify-2fa',
  path: '/auth/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAnalyticsRoute,
} as any)
const DashboardSettingsWorkspaceRoute =
  DashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsTemplatesRoute =
  DashboardSettingsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsTeamManagementRoute =
  DashboardSettingsTeamManagementRouteImport.update({
    id: '/team-management',
    path: '/team-management',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsShortcutsRoute =
  DashboardSettingsShortcutsRouteImport.update({
    id: '/shortcuts',
    path: '/shortcuts',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRolesUnifiedRoute =
  DashboardSettingsRolesUnifiedRouteImport.update({
    id: '/roles-unified',
    path: '/roles-unified',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsLocalizationRoute =
  DashboardSettingsLocalizationRouteImport.update({
    id: '/localization',
    path: '/localization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsFiltersRoute =
  DashboardSettingsFiltersRouteImport.update({
    id: '/filters',
    path: '/filters',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsEmailRoute = DashboardSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsDataManagementRoute =
  DashboardSettingsDataManagementRouteImport.update({
    id: '/data-management',
    path: '/data-management',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsCalendarRoute =
  DashboardSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAuditLogsRoute =
  DashboardSettingsAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsApiRoute = DashboardSettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsLayoutRoute = DashboardSettingsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardProfileUserIdRoute = DashboardProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsScheduledRoute =
  DashboardAnalyticsScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => DashboardAnalyticsRoute,
  } as any)
const DashboardAnalyticsBuilderRoute =
  DashboardAnalyticsBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => DashboardAnalyticsRoute,
  } as any)
const DashboardAdminRolesRoute = DashboardAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceSettingsWorkspaceIdIndexRoute =
  DashboardWorkspaceSettingsWorkspaceIdIndexRouteImport.update({
    id: '/workspace-settings/$workspaceId/',
    path: '/workspace-settings/$workspaceId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdTemplatesRoute =
  DashboardWorkspaceWorkspaceIdTemplatesRouteImport.update({
    id: '/workspace/$workspaceId/templates',
    path: '/workspace/$workspaceId/templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeamsWorkspaceIdLayoutRoute =
  DashboardTeamsWorkspaceIdLayoutRouteImport.update({
    id: '/$workspaceId/_layout',
    path: '/$workspaceId',
    getParentRoute: () => DashboardTeamsRoute,
  } as any)
const DashboardSettingsRolesUnifiedRoleIdRoute =
  DashboardSettingsRolesUnifiedRoleIdRouteImport.update({
    id: '/$roleId',
    path: '/$roleId',
    getParentRoute: () => DashboardSettingsRolesUnifiedRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdRouteImport.update({
    id: '/workspace/$workspaceId/project/$projectId',
    path: '/workspace/$workspaceId/project/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeamsWorkspaceIdLayoutRolesRoute =
  DashboardTeamsWorkspaceIdLayoutRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => DashboardTeamsWorkspaceIdLayoutRoute,
  } as any)
const DashboardTeamsWorkspaceIdLayoutMembersRoute =
  DashboardTeamsWorkspaceIdLayoutMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardTeamsWorkspaceIdLayoutRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdProjectProjectIdRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRouteImport.update(
    {
      id: '/timeline',
      path: '/timeline',
      getParentRoute: () =>
        DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute,
    } as any,
  )
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () =>
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () =>
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRouteImport.update(
    {
      id: '/calendar',
      path: '/calendar',
      getParentRoute: () =>
        DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/all-tasks': typeof DashboardAllTasksRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac-explanation': typeof DashboardRbacExplanationRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsLayoutRoute
  '/dashboard/teams': typeof DashboardTeamsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/analytics/builder': typeof DashboardAnalyticsBuilderRoute
  '/dashboard/analytics/scheduled': typeof DashboardAnalyticsScheduledRoute
  '/dashboard/profile/$userId': typeof DashboardProfileUserIdRoute
  '/dashboard/settings/api': typeof DashboardSettingsApiRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/calendar': typeof DashboardSettingsCalendarRoute
  '/dashboard/settings/data-management': typeof DashboardSettingsDataManagementRoute
  '/dashboard/settings/email': typeof DashboardSettingsEmailRoute
  '/dashboard/settings/filters': typeof DashboardSettingsFiltersRoute
  '/dashboard/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/roles-unified': typeof DashboardSettingsRolesUnifiedRouteWithChildren
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/shortcuts': typeof DashboardSettingsShortcutsRoute
  '/dashboard/settings/team-management': typeof DashboardSettingsTeamManagementRoute
  '/dashboard/settings/templates': typeof DashboardSettingsTemplatesRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/roles-unified/$roleId': typeof DashboardSettingsRolesUnifiedRoleIdRoute
  '/dashboard/teams/$workspaceId': typeof DashboardTeamsWorkspaceIdLayoutRouteWithChildren
  '/dashboard/workspace/$workspaceId/templates': typeof DashboardWorkspaceWorkspaceIdTemplatesRoute
  '/dashboard/workspace-settings/$workspaceId/': typeof DashboardWorkspaceSettingsWorkspaceIdIndexRoute
  '/dashboard/teams/$workspaceId/members': typeof DashboardTeamsWorkspaceIdLayoutMembersRoute
  '/dashboard/teams/$workspaceId/roles': typeof DashboardTeamsWorkspaceIdLayoutRolesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteWithChildren
  '/dashboard/workspace/$workspaceId/project/$projectId/analytics': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/milestones': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/notes': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/calendar': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/list': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/teams': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/timeline': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/all-tasks': typeof DashboardAllTasksRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac-explanation': typeof DashboardRbacExplanationRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/teams': typeof DashboardTeamsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/analytics/builder': typeof DashboardAnalyticsBuilderRoute
  '/dashboard/analytics/scheduled': typeof DashboardAnalyticsScheduledRoute
  '/dashboard/profile/$userId': typeof DashboardProfileUserIdRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/api': typeof DashboardSettingsApiRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/calendar': typeof DashboardSettingsCalendarRoute
  '/dashboard/settings/data-management': typeof DashboardSettingsDataManagementRoute
  '/dashboard/settings/email': typeof DashboardSettingsEmailRoute
  '/dashboard/settings/filters': typeof DashboardSettingsFiltersRoute
  '/dashboard/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/roles-unified': typeof DashboardSettingsRolesUnifiedRouteWithChildren
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/shortcuts': typeof DashboardSettingsShortcutsRoute
  '/dashboard/settings/team-management': typeof DashboardSettingsTeamManagementRoute
  '/dashboard/settings/templates': typeof DashboardSettingsTemplatesRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings/roles-unified/$roleId': typeof DashboardSettingsRolesUnifiedRoleIdRoute
  '/dashboard/teams/$workspaceId': typeof DashboardTeamsWorkspaceIdLayoutRouteWithChildren
  '/dashboard/workspace/$workspaceId/templates': typeof DashboardWorkspaceWorkspaceIdTemplatesRoute
  '/dashboard/workspace-settings/$workspaceId': typeof DashboardWorkspaceSettingsWorkspaceIdIndexRoute
  '/dashboard/teams/$workspaceId/members': typeof DashboardTeamsWorkspaceIdLayoutMembersRoute
  '/dashboard/teams/$workspaceId/roles': typeof DashboardTeamsWorkspaceIdLayoutRolesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/analytics': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/milestones': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/notes': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/calendar': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/list': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/teams': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/timeline': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/all-tasks': typeof DashboardAllTasksRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac-explanation': typeof DashboardRbacExplanationRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/analytics/builder': typeof DashboardAnalyticsBuilderRoute
  '/dashboard/analytics/scheduled': typeof DashboardAnalyticsScheduledRoute
  '/dashboard/profile/$userId': typeof DashboardProfileUserIdRoute
  '/dashboard/settings/_layout': typeof DashboardSettingsLayoutRoute
  '/dashboard/settings/api': typeof DashboardSettingsApiRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/calendar': typeof DashboardSettingsCalendarRoute
  '/dashboard/settings/data-management': typeof DashboardSettingsDataManagementRoute
  '/dashboard/settings/email': typeof DashboardSettingsEmailRoute
  '/dashboard/settings/filters': typeof DashboardSettingsFiltersRoute
  '/dashboard/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/settings/roles-unified': typeof DashboardSettingsRolesUnifiedRouteWithChildren
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/shortcuts': typeof DashboardSettingsShortcutsRoute
  '/dashboard/settings/team-management': typeof DashboardSettingsTeamManagementRoute
  '/dashboard/settings/templates': typeof DashboardSettingsTemplatesRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/roles-unified/$roleId': typeof DashboardSettingsRolesUnifiedRoleIdRoute
  '/dashboard/teams/$workspaceId/_layout': typeof DashboardTeamsWorkspaceIdLayoutRouteWithChildren
  '/dashboard/workspace/$workspaceId/templates': typeof DashboardWorkspaceWorkspaceIdTemplatesRoute
  '/dashboard/workspace-settings/$workspaceId/': typeof DashboardWorkspaceSettingsWorkspaceIdIndexRoute
  '/dashboard/teams/$workspaceId/_layout/members': typeof DashboardTeamsWorkspaceIdLayoutMembersRoute
  '/dashboard/teams/$workspaceId/_layout/roles': typeof DashboardTeamsWorkspaceIdLayoutRolesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRouteWithChildren
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteWithChildren
  '/dashboard/workspace/$workspaceId/project/$projectId/analytics': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/milestones': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/notes': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/settings': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout/calendar': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout/list': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout/teams': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout/timeline': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/_layout/': typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/dashboard/activity'
    | '/dashboard/all-tasks'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/calendar'
    | '/dashboard/projects'
    | '/dashboard/rbac-explanation'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/'
    | '/dashboard/admin/roles'
    | '/dashboard/analytics/builder'
    | '/dashboard/analytics/scheduled'
    | '/dashboard/profile/$userId'
    | '/dashboard/settings/api'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/calendar'
    | '/dashboard/settings/data-management'
    | '/dashboard/settings/email'
    | '/dashboard/settings/filters'
    | '/dashboard/settings/localization'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/roles-unified'
    | '/dashboard/settings/security'
    | '/dashboard/settings/shortcuts'
    | '/dashboard/settings/team-management'
    | '/dashboard/settings/templates'
    | '/dashboard/settings/workspace'
    | '/dashboard/analytics/'
    | '/dashboard/notifications/'
    | '/dashboard/settings/'
    | '/dashboard/settings/roles-unified/$roleId'
    | '/dashboard/teams/$workspaceId'
    | '/dashboard/workspace/$workspaceId/templates'
    | '/dashboard/workspace-settings/$workspaceId/'
    | '/dashboard/teams/$workspaceId/members'
    | '/dashboard/teams/$workspaceId/roles'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/analytics'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/milestones'
    | '/dashboard/workspace/$workspaceId/project/$projectId/notes'
    | '/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/dashboard/workspace/$workspaceId/project/$projectId/calendar'
    | '/dashboard/workspace/$workspaceId/project/$projectId/list'
    | '/dashboard/workspace/$workspaceId/project/$projectId/teams'
    | '/dashboard/workspace/$workspaceId/project/$projectId/timeline'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/dashboard/activity'
    | '/dashboard/all-tasks'
    | '/dashboard/audit'
    | '/dashboard/calendar'
    | '/dashboard/projects'
    | '/dashboard/rbac-explanation'
    | '/dashboard/security'
    | '/dashboard/teams'
    | '/dashboard'
    | '/dashboard/admin/roles'
    | '/dashboard/analytics/builder'
    | '/dashboard/analytics/scheduled'
    | '/dashboard/profile/$userId'
    | '/dashboard/settings'
    | '/dashboard/settings/api'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/calendar'
    | '/dashboard/settings/data-management'
    | '/dashboard/settings/email'
    | '/dashboard/settings/filters'
    | '/dashboard/settings/localization'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/roles-unified'
    | '/dashboard/settings/security'
    | '/dashboard/settings/shortcuts'
    | '/dashboard/settings/team-management'
    | '/dashboard/settings/templates'
    | '/dashboard/settings/workspace'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/settings/roles-unified/$roleId'
    | '/dashboard/teams/$workspaceId'
    | '/dashboard/workspace/$workspaceId/templates'
    | '/dashboard/workspace-settings/$workspaceId'
    | '/dashboard/teams/$workspaceId/members'
    | '/dashboard/teams/$workspaceId/roles'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/analytics'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/milestones'
    | '/dashboard/workspace/$workspaceId/project/$projectId/notes'
    | '/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/dashboard/workspace/$workspaceId/project/$projectId/calendar'
    | '/dashboard/workspace/$workspaceId/project/$projectId/list'
    | '/dashboard/workspace/$workspaceId/project/$projectId/teams'
    | '/dashboard/workspace/$workspaceId/project/$projectId/timeline'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/dashboard/activity'
    | '/dashboard/all-tasks'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/calendar'
    | '/dashboard/projects'
    | '/dashboard/rbac-explanation'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/'
    | '/dashboard/admin/roles'
    | '/dashboard/analytics/builder'
    | '/dashboard/analytics/scheduled'
    | '/dashboard/profile/$userId'
    | '/dashboard/settings/_layout'
    | '/dashboard/settings/api'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/calendar'
    | '/dashboard/settings/data-management'
    | '/dashboard/settings/email'
    | '/dashboard/settings/filters'
    | '/dashboard/settings/localization'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/roles-unified'
    | '/dashboard/settings/security'
    | '/dashboard/settings/shortcuts'
    | '/dashboard/settings/team-management'
    | '/dashboard/settings/templates'
    | '/dashboard/settings/workspace'
    | '/dashboard/analytics/'
    | '/dashboard/notifications/'
    | '/dashboard/settings/'
    | '/dashboard/settings/roles-unified/$roleId'
    | '/dashboard/teams/$workspaceId/_layout'
    | '/dashboard/workspace/$workspaceId/templates'
    | '/dashboard/workspace-settings/$workspaceId/'
    | '/dashboard/teams/$workspaceId/_layout/members'
    | '/dashboard/teams/$workspaceId/_layout/roles'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout'
    | '/dashboard/workspace/$workspaceId/project/$projectId/analytics'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/milestones'
    | '/dashboard/workspace/$workspaceId/project/$projectId/notes'
    | '/dashboard/workspace/$workspaceId/project/$projectId/settings'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout/calendar'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout/list'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout/teams'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout/timeline'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerify2faRoute: typeof AuthVerify2faRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rbac-explanation': {
      id: '/dashboard/rbac-explanation'
      path: '/rbac-explanation'
      fullPath: '/dashboard/rbac-explanation'
      preLoaderRoute: typeof DashboardRbacExplanationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/all-tasks': {
      id: '/dashboard/all-tasks'
      path: '/all-tasks'
      fullPath: '/dashboard/all-tasks'
      preLoaderRoute: typeof DashboardAllTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify-2fa': {
      id: '/auth/verify-2fa'
      path: '/auth/verify-2fa'
      fullPath: '/auth/verify-2fa'
      preLoaderRoute: typeof AuthVerify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardAnalyticsRoute
    }
    '/dashboard/settings/workspace': {
      id: '/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof DashboardSettingsWorkspaceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/templates': {
      id: '/dashboard/settings/templates'
      path: '/templates'
      fullPath: '/dashboard/settings/templates'
      preLoaderRoute: typeof DashboardSettingsTemplatesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/team-management': {
      id: '/dashboard/settings/team-management'
      path: '/team-management'
      fullPath: '/dashboard/settings/team-management'
      preLoaderRoute: typeof DashboardSettingsTeamManagementRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/shortcuts': {
      id: '/dashboard/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/dashboard/settings/shortcuts'
      preLoaderRoute: typeof DashboardSettingsShortcutsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/roles-unified': {
      id: '/dashboard/settings/roles-unified'
      path: '/roles-unified'
      fullPath: '/dashboard/settings/roles-unified'
      preLoaderRoute: typeof DashboardSettingsRolesUnifiedRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/localization': {
      id: '/dashboard/settings/localization'
      path: '/localization'
      fullPath: '/dashboard/settings/localization'
      preLoaderRoute: typeof DashboardSettingsLocalizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/filters': {
      id: '/dashboard/settings/filters'
      path: '/filters'
      fullPath: '/dashboard/settings/filters'
      preLoaderRoute: typeof DashboardSettingsFiltersRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/email': {
      id: '/dashboard/settings/email'
      path: '/email'
      fullPath: '/dashboard/settings/email'
      preLoaderRoute: typeof DashboardSettingsEmailRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/data-management': {
      id: '/dashboard/settings/data-management'
      path: '/data-management'
      fullPath: '/dashboard/settings/data-management'
      preLoaderRoute: typeof DashboardSettingsDataManagementRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/calendar': {
      id: '/dashboard/settings/calendar'
      path: '/calendar'
      fullPath: '/dashboard/settings/calendar'
      preLoaderRoute: typeof DashboardSettingsCalendarRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/audit-logs': {
      id: '/dashboard/settings/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/settings/audit-logs'
      preLoaderRoute: typeof DashboardSettingsAuditLogsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/api': {
      id: '/dashboard/settings/api'
      path: '/api'
      fullPath: '/dashboard/settings/api'
      preLoaderRoute: typeof DashboardSettingsApiRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/_layout': {
      id: '/dashboard/settings/_layout'
      path: ''
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLayoutRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/profile/$userId': {
      id: '/dashboard/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/dashboard/profile/$userId'
      preLoaderRoute: typeof DashboardProfileUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/scheduled': {
      id: '/dashboard/analytics/scheduled'
      path: '/scheduled'
      fullPath: '/dashboard/analytics/scheduled'
      preLoaderRoute: typeof DashboardAnalyticsScheduledRouteImport
      parentRoute: typeof DashboardAnalyticsRoute
    }
    '/dashboard/analytics/builder': {
      id: '/dashboard/analytics/builder'
      path: '/builder'
      fullPath: '/dashboard/analytics/builder'
      preLoaderRoute: typeof DashboardAnalyticsBuilderRouteImport
      parentRoute: typeof DashboardAnalyticsRoute
    }
    '/dashboard/admin/roles': {
      id: '/dashboard/admin/roles'
      path: '/admin/roles'
      fullPath: '/dashboard/admin/roles'
      preLoaderRoute: typeof DashboardAdminRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace-settings/$workspaceId/': {
      id: '/dashboard/workspace-settings/$workspaceId/'
      path: '/workspace-settings/$workspaceId'
      fullPath: '/dashboard/workspace-settings/$workspaceId/'
      preLoaderRoute: typeof DashboardWorkspaceSettingsWorkspaceIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace/$workspaceId/templates': {
      id: '/dashboard/workspace/$workspaceId/templates'
      path: '/workspace/$workspaceId/templates'
      fullPath: '/dashboard/workspace/$workspaceId/templates'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams/$workspaceId/_layout': {
      id: '/dashboard/teams/$workspaceId/_layout'
      path: '/$workspaceId'
      fullPath: '/dashboard/teams/$workspaceId'
      preLoaderRoute: typeof DashboardTeamsWorkspaceIdLayoutRouteImport
      parentRoute: typeof DashboardTeamsRoute
    }
    '/dashboard/settings/roles-unified/$roleId': {
      id: '/dashboard/settings/roles-unified/$roleId'
      path: '/$roleId'
      fullPath: '/dashboard/settings/roles-unified/$roleId'
      preLoaderRoute: typeof DashboardSettingsRolesUnifiedRoleIdRouteImport
      parentRoute: typeof DashboardSettingsRolesUnifiedRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId'
      path: '/workspace/$workspaceId/project/$projectId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams/$workspaceId/_layout/roles': {
      id: '/dashboard/teams/$workspaceId/_layout/roles'
      path: '/roles'
      fullPath: '/dashboard/teams/$workspaceId/roles'
      preLoaderRoute: typeof DashboardTeamsWorkspaceIdLayoutRolesRouteImport
      parentRoute: typeof DashboardTeamsWorkspaceIdLayoutRoute
    }
    '/dashboard/teams/$workspaceId/_layout/members': {
      id: '/dashboard/teams/$workspaceId/_layout/members'
      path: '/members'
      fullPath: '/dashboard/teams/$workspaceId/members'
      preLoaderRoute: typeof DashboardTeamsWorkspaceIdLayoutMembersRouteImport
      parentRoute: typeof DashboardTeamsWorkspaceIdLayoutRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/settings': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/settings'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/notes': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/notes'
      path: '/notes'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/notes'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/milestones': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/milestones'
      path: '/milestones'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/milestones'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/board': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/board'
      path: '/board'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/board'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/backlog': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      path: '/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/analytics': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/analytics'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout'
      path: ''
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout/': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout/timeline': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout/timeline'
      path: '/timeline'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/timeline'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout/teams': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout/teams'
      path: '/teams'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/teams'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout/list': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout/list'
      path: '/list'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/list'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute
    }
    '/dashboard/workspace/$workspaceId/project/$projectId/_layout/calendar': {
      id: '/dashboard/workspace/$workspaceId/project/$projectId/_layout/calendar'
      path: '/calendar'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/calendar'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute
    }
  }
}

interface DashboardAnalyticsRouteChildren {
  DashboardAnalyticsBuilderRoute: typeof DashboardAnalyticsBuilderRoute
  DashboardAnalyticsScheduledRoute: typeof DashboardAnalyticsScheduledRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
}

const DashboardAnalyticsRouteChildren: DashboardAnalyticsRouteChildren = {
  DashboardAnalyticsBuilderRoute: DashboardAnalyticsBuilderRoute,
  DashboardAnalyticsScheduledRoute: DashboardAnalyticsScheduledRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
}

const DashboardAnalyticsRouteWithChildren =
  DashboardAnalyticsRoute._addFileChildren(DashboardAnalyticsRouteChildren)

interface DashboardSettingsRolesUnifiedRouteChildren {
  DashboardSettingsRolesUnifiedRoleIdRoute: typeof DashboardSettingsRolesUnifiedRoleIdRoute
}

const DashboardSettingsRolesUnifiedRouteChildren: DashboardSettingsRolesUnifiedRouteChildren =
  {
    DashboardSettingsRolesUnifiedRoleIdRoute:
      DashboardSettingsRolesUnifiedRoleIdRoute,
  }

const DashboardSettingsRolesUnifiedRouteWithChildren =
  DashboardSettingsRolesUnifiedRoute._addFileChildren(
    DashboardSettingsRolesUnifiedRouteChildren,
  )

interface DashboardSettingsRouteChildren {
  DashboardSettingsLayoutRoute: typeof DashboardSettingsLayoutRoute
  DashboardSettingsApiRoute: typeof DashboardSettingsApiRoute
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsAuditLogsRoute: typeof DashboardSettingsAuditLogsRoute
  DashboardSettingsCalendarRoute: typeof DashboardSettingsCalendarRoute
  DashboardSettingsDataManagementRoute: typeof DashboardSettingsDataManagementRoute
  DashboardSettingsEmailRoute: typeof DashboardSettingsEmailRoute
  DashboardSettingsFiltersRoute: typeof DashboardSettingsFiltersRoute
  DashboardSettingsLocalizationRoute: typeof DashboardSettingsLocalizationRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsRolesUnifiedRoute: typeof DashboardSettingsRolesUnifiedRouteWithChildren
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsShortcutsRoute: typeof DashboardSettingsShortcutsRoute
  DashboardSettingsTeamManagementRoute: typeof DashboardSettingsTeamManagementRoute
  DashboardSettingsTemplatesRoute: typeof DashboardSettingsTemplatesRoute
  DashboardSettingsWorkspaceRoute: typeof DashboardSettingsWorkspaceRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsLayoutRoute: DashboardSettingsLayoutRoute,
  DashboardSettingsApiRoute: DashboardSettingsApiRoute,
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsAuditLogsRoute: DashboardSettingsAuditLogsRoute,
  DashboardSettingsCalendarRoute: DashboardSettingsCalendarRoute,
  DashboardSettingsDataManagementRoute: DashboardSettingsDataManagementRoute,
  DashboardSettingsEmailRoute: DashboardSettingsEmailRoute,
  DashboardSettingsFiltersRoute: DashboardSettingsFiltersRoute,
  DashboardSettingsLocalizationRoute: DashboardSettingsLocalizationRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsRolesUnifiedRoute:
    DashboardSettingsRolesUnifiedRouteWithChildren,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsShortcutsRoute: DashboardSettingsShortcutsRoute,
  DashboardSettingsTeamManagementRoute: DashboardSettingsTeamManagementRoute,
  DashboardSettingsTemplatesRoute: DashboardSettingsTemplatesRoute,
  DashboardSettingsWorkspaceRoute: DashboardSettingsWorkspaceRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardTeamsWorkspaceIdLayoutRouteChildren {
  DashboardTeamsWorkspaceIdLayoutMembersRoute: typeof DashboardTeamsWorkspaceIdLayoutMembersRoute
  DashboardTeamsWorkspaceIdLayoutRolesRoute: typeof DashboardTeamsWorkspaceIdLayoutRolesRoute
}

const DashboardTeamsWorkspaceIdLayoutRouteChildren: DashboardTeamsWorkspaceIdLayoutRouteChildren =
  {
    DashboardTeamsWorkspaceIdLayoutMembersRoute:
      DashboardTeamsWorkspaceIdLayoutMembersRoute,
    DashboardTeamsWorkspaceIdLayoutRolesRoute:
      DashboardTeamsWorkspaceIdLayoutRolesRoute,
  }

const DashboardTeamsWorkspaceIdLayoutRouteWithChildren =
  DashboardTeamsWorkspaceIdLayoutRoute._addFileChildren(
    DashboardTeamsWorkspaceIdLayoutRouteChildren,
  )

interface DashboardTeamsRouteChildren {
  DashboardTeamsWorkspaceIdLayoutRoute: typeof DashboardTeamsWorkspaceIdLayoutRouteWithChildren
}

const DashboardTeamsRouteChildren: DashboardTeamsRouteChildren = {
  DashboardTeamsWorkspaceIdLayoutRoute:
    DashboardTeamsWorkspaceIdLayoutRouteWithChildren,
}

const DashboardTeamsRouteWithChildren = DashboardTeamsRoute._addFileChildren(
  DashboardTeamsRouteChildren,
)

interface DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteChildren {
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute
}

const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteChildren: DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteChildren =
  {
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutCalendarRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutListRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTeamsRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutTimelineRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutIndexRoute,
  }

const DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteWithChildren =
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute._addFileChildren(
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteChildren,
  )

interface DashboardWorkspaceWorkspaceIdProjectProjectIdRouteChildren {
  DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteWithChildren
  DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}

const DashboardWorkspaceWorkspaceIdProjectProjectIdRouteChildren: DashboardWorkspaceWorkspaceIdProjectProjectIdRouteChildren =
  {
    DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdLayoutRouteWithChildren,
    DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdAnalyticsRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdMilestonesRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdNotesRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdSettingsRoute,
    DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute:
      DashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute,
  }

const DashboardWorkspaceWorkspaceIdProjectProjectIdRouteWithChildren =
  DashboardWorkspaceWorkspaceIdProjectProjectIdRoute._addFileChildren(
    DashboardWorkspaceWorkspaceIdProjectProjectIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAllTasksRoute: typeof DashboardAllTasksRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRouteWithChildren
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRbacExplanationRoute: typeof DashboardRbacExplanationRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardTeamsRoute: typeof DashboardTeamsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminRolesRoute: typeof DashboardAdminRolesRoute
  DashboardProfileUserIdRoute: typeof DashboardProfileUserIdRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardWorkspaceWorkspaceIdTemplatesRoute: typeof DashboardWorkspaceWorkspaceIdTemplatesRoute
  DashboardWorkspaceSettingsWorkspaceIdIndexRoute: typeof DashboardWorkspaceSettingsWorkspaceIdIndexRoute
  DashboardWorkspaceWorkspaceIdProjectProjectIdRoute: typeof DashboardWorkspaceWorkspaceIdProjectProjectIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAllTasksRoute: DashboardAllTasksRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRouteWithChildren,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRbacExplanationRoute: DashboardRbacExplanationRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardTeamsRoute: DashboardTeamsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminRolesRoute: DashboardAdminRolesRoute,
  DashboardProfileUserIdRoute: DashboardProfileUserIdRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardWorkspaceWorkspaceIdTemplatesRoute:
    DashboardWorkspaceWorkspaceIdTemplatesRoute,
  DashboardWorkspaceSettingsWorkspaceIdIndexRoute:
    DashboardWorkspaceSettingsWorkspaceIdIndexRoute,
  DashboardWorkspaceWorkspaceIdProjectProjectIdRoute:
    DashboardWorkspaceWorkspaceIdProjectProjectIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
