/**
 * 🛡️ Permission Definitions & Role Permissions Matrix
 * 
 * Central configuration for all role permissions and hierarchies.
 * Used by both frontend components and backend middleware.
 * 
 * @epic-1.1-subtasks - Team leads have special subtask management powers
 * @epic-2.1-files - File access based on role
 * @epic-3.2-time - Time tracking permissions by role
 */

import type { UserRole, AllPermissions } from "./types";

/**
 * Role hierarchy levels - higher numbers = more permissions
 */
export const ROLE_HIERARCHY: Record<UserRole, number> = {
  "guest": 0,
  "stakeholder": 1,
  "contractor": 1,
  "client": 1,
  "member": 1,
  "team-lead": 2,          // @epic-1.1-subtasks - Enhanced subtask powers
  "project-viewer": 3,
  "project-manager": 4,
  "workspace-viewer": 5,
  "department-head": 6,
  "workspace-manager": 7,
};

/**
 * Base permissions for guest role (all false)
 */
const BASE_PERMISSIONS: Omit<AllPermissions, "role"> = {
  // Workspace permissions
  canManageWorkspace: false,
  canViewWorkspace: false,
  canDeleteWorkspace: false,
  canManageWorkspaceSettings: false,
  canManageBilling: false,
  canViewBillingHistory: false,
  canChangePlan: false,
  canInviteUsers: false,
  canRemoveUsers: false,
  canManageRoles: false,
  canAssignDepartmentHeads: false,
  canViewAllUsers: false,
  canViewWorkspaceAnalytics: false,
  canExportWorkspaceData: false,
  canCreateWorkspaceReports: false,
  canScheduleReports: false,
  canManageIntegrations: false,
  canAccessWorkspaceAPI: false,
  canManageWorkspaceSecurity: false,
  canViewAuditLogs: false,
  canManageBackups: false,

  // Project permissions
  canCreateProjects: false,
  canEditProjects: false,
  canDeleteProjects: false,
  canArchiveProjects: false,
  canCloneProjects: false,
  canManageProjectSettings: false,
  canManageProjectTeam: false,
  canAssignProjectManagers: false,
  canInviteToProject: false,
  canRemoveFromProject: false,
  canViewAllProjects: false,
  canViewAssignedProjects: false,
  canViewProjectDetails: false,
  canAccessProjectFiles: false,
  canViewProjectAnalytics: false,
  canViewProjectReports: false,
  canExportProjectData: false,
  canViewProjectBudget: false,
  canManageProjectBudget: false,
  canAccessProjectChat: false,
  canCreateProjectAnnouncements: false,
  canModerateProjectDiscussion: false,

  // Task permissions
  canCreateTasks: false,
  canEditTasks: false,
  canDeleteTasks: false,
  canViewTasks: false,
  canViewAllTasks: false,
  canAssignTasks: false,
  canReassignTasks: false,
  canAssignTasksToMembers: false,
  canUnassignTasks: false,
  canCreateSubtasks: false,
  canEditSubtasks: false,
  canDeleteSubtasks: false,
  canAssignSubtasks: false,
  canManageSubtaskHierarchy: false,
  canSetTaskPriority: false,
  canSetTaskDeadlines: false,
  canSetTaskStatus: false,
  canAddTaskLabels: false,
  canManageTaskDependencies: false,
  canCommentOnTasks: false,
  canMentionUsersInTasks: false,
  canAttachFilesToTasks: false,
  canLogTimeOnTasks: false,
  canBulkEditTasks: false,
  canBulkAssignTasks: false,
  canImportTasks: false,
  canExportTasks: false,

  // Team permissions
  canCreateTeams: false,
  canEditTeams: false,
  canDeleteTeams: false,
  canArchiveTeams: false,
  canAddMembers: false,
  canRemoveMembers: false,
  canInviteMembers: false,
  canManageTeamRoles: false,
  canViewTeamMembers: false,
  canAssignTeamLeads: false,
  canMentorMembers: false,
  canViewTeamProgress: false,
  canManageTeamCapacity: false,
  canCreateTeamChannels: false,
  canManageTeamChannels: false,
  canModerateTeamChat: false,
  canCreateTeamAnnouncements: false,

  // Communication permissions
  canSendMessages: false,
  canSendDirectMessages: false,
  canMentionUsers: false,
  canReactToMessages: false,
  canCreateChannels: false,
  canJoinChannels: false,
  canLeaveChannels: false,
  canManageChannels: false,
  canArchiveChannels: false,
  canModerateChat: false,
  canDeleteMessages: false,
  canPinMessages: false,
  canManageChannelPermissions: false,
  canStartVideoCall: false,
  canShareScreen: false,
  canRecordMeetings: false,
  canScheduleMeetings: false,

  // Resource permissions
  canUploadFiles: false,
  canDownloadFiles: false,
  canDeleteFiles: false,
  canOrganizeFiles: false,
  canShareFiles: false,
  canManageFileVersions: false,
  canViewCalendar: false,
  canCreateEvents: false,
  canEditEvents: false,
  canDeleteEvents: false,
  canManageAvailability: false,
  canBookResources: false,
  canManageTimeOff: false,
  canTrackTime: false,
  canViewTimeTracking: false,
  canEditTimeEntries: false,
  canApproveTimeEntries: false,
  canManageTimeTracking: false,
  canAccessKnowledgeBase: false,
  canCreateDocuments: false,
  canEditDocuments: false,
  canDeleteDocuments: false,
  canManageDocumentPermissions: false,

  // Analytics permissions
  canViewAnalytics: false,
  canViewPersonalAnalytics: false,
  canViewTeamAnalytics: false,
  canViewTeamPerformance: false,
  canViewIndividualPerformance: false,
  canViewProductivityMetrics: false,
  canViewBudgetAnalytics: false,
  canViewTimeReports: false,
  canCreateReports: false,
  canCustomizeReports: false,
  canExportReports: false,
  canShareReports: false,
  canAccessAdvancedAnalytics: false,
  canCreateDashboards: false,
  canManageDashboards: false,
  canCreateCustomMetrics: false,

  // System permissions
  canAccessSystemSettings: false,
  canManageSystemIntegrations: false,
  canManageAPIAccess: false,
  canViewSystemHealth: false,
  canManageSystemBackups: false,
  canManageSecurity: false,
  canViewSecurityLogs: false,
  canManageSSO: false,
  canManage2FA: false,
  canManageDataRetention: false,
  canAccessAuditLogs: false,
  canManageCompliance: false,
  canExportAuditData: false,
  canManageDataGovernance: false,
  canAccessBetaFeatures: false,
  canUseAI: false,
  canManageAISettings: false,
  canAccessDeveloperTools: false,
};

/**
 * Complete role permissions matrix
 */
export const ROLE_PERMISSIONS: Record<UserRole, AllPermissions> = {
  // ===== GUEST (Level 0) =====
  "guest": {
    ...BASE_PERMISSIONS,
    role: "guest",
  },

  // ===== STAKEHOLDER (Level 1) =====
  "stakeholder": {
    ...BASE_PERMISSIONS,
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCommentOnTasks: true,
    canViewAnalytics: true,
    role: "stakeholder",
  },

  // ===== CONTRACTOR (Level 1) =====
  "contractor": {
    ...BASE_PERMISSIONS,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canEditTasks: true,
    canCommentOnTasks: true,
    canLogTimeOnTasks: true,
    canTrackTime: true,
    role: "contractor",
  },

  // ===== CLIENT (Level 1) =====
  "client": {
    ...BASE_PERMISSIONS,
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCommentOnTasks: true,
    canViewAnalytics: true,
    role: "client",
  },

  // ===== MEMBER (Level 1) =====
  "member": {
    ...BASE_PERMISSIONS,
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCreateTasks: true,
    canEditTasks: true,
    canCommentOnTasks: true,
    canLogTimeOnTasks: true,
    canTrackTime: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canUploadFiles: true,
    canDownloadFiles: true,
    canShareFiles: true,
    canViewCalendar: true,
    canAccessKnowledgeBase: true,
    // Grant analytics/reporting permissions for demo/testing @epic-3.1-analytics
    canViewAnalytics: true, // Added for analytics dashboard access
    canCreateReports: true, // Added for report builder access
    role: "member",
  },

  // ===== TEAM LEAD (Level 2) - @epic-1.1-subtasks Special Powers =====
  "team-lead": {
    ...BASE_PERMISSIONS,
    // Inherit member permissions
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCreateTasks: true,
    canEditTasks: true,
    canCommentOnTasks: true,
    canLogTimeOnTasks: true,
    canTrackTime: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canUploadFiles: true,
    canDownloadFiles: true,
    canShareFiles: true,
    canViewCalendar: true,
    canAccessKnowledgeBase: true,
    // Team lead specific permissions
    canAssignTasks: true,
    canReassignTasks: true,
    canAssignTasksToMembers: true,
    // 🌟 TEAM LEAD SPECIAL SUBTASK POWERS - @epic-1.1-subtasks
    canCreateSubtasks: true,
    canEditSubtasks: true,
    canDeleteSubtasks: true,
    canAssignSubtasks: true,
    canManageSubtaskHierarchy: true,
    canSetTaskPriority: true,
    canSetTaskDeadlines: true,
    canSetTaskStatus: true,
    canAddTaskLabels: true,
    canViewTeamProgress: true,
    canManageTeamCapacity: true,
    canMentorMembers: true,
    canViewAnalytics: true,
    canViewTeamAnalytics: true,
    canViewPersonalAnalytics: true,
    canViewTimeReports: true,
    role: "team-lead",
  },

  // ===== PROJECT VIEWER (Level 3) =====
  "project-viewer": {
    ...BASE_PERMISSIONS,
    // Basic viewing permissions
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewAllProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCommentOnTasks: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canDownloadFiles: true,
    canShareFiles: true,
    canViewCalendar: true,
    canAccessKnowledgeBase: true,
    // Project viewer specific
    canViewProjectAnalytics: true,
    canViewProjectReports: true,
    canExportProjectData: true,
    canViewAnalytics: true,
    role: "project-viewer",
  },

  // ===== PROJECT MANAGER (Level 4) =====
  "project-manager": {
    ...BASE_PERMISSIONS,
    // Inherit team lead permissions
    canViewWorkspace: true,
    canViewAssignedProjects: true,
    canViewAllProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canViewAllTasks: true,
    canCreateTasks: true,
    canEditTasks: true,
    canDeleteTasks: true,
    canCommentOnTasks: true,
    canLogTimeOnTasks: true,
    canTrackTime: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canUploadFiles: true,
    canDownloadFiles: true,
    canDeleteFiles: true,
    canOrganizeFiles: true,
    canShareFiles: true,
    canManageFileVersions: true,
    canViewCalendar: true,
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: true,
    canAccessKnowledgeBase: true,
    canCreateDocuments: true,
    canEditDocuments: true,
    canDeleteDocuments: true,
    canAssignTasks: true,
    canReassignTasks: true,
    canAssignTasksToMembers: true,
    canUnassignTasks: true,
    canCreateSubtasks: true,
    canEditSubtasks: true,
    canDeleteSubtasks: true,
    canAssignSubtasks: true,
    canManageSubtaskHierarchy: true,
    canSetTaskPriority: true,
    canSetTaskDeadlines: true,
    canSetTaskStatus: true,
    canAddTaskLabels: true,
    canManageTaskDependencies: true,
    canMentionUsersInTasks: true,
    canAttachFilesToTasks: true,
    canViewTeamProgress: true,
    canManageTeamCapacity: true,
    canMentorMembers: true,
    canViewAnalytics: true,
    canViewTeamAnalytics: true,
    canViewPersonalAnalytics: true,
    canViewTimeReports: true,
    canViewTimeTracking: true,
    canEditTimeEntries: true,
    canApproveTimeEntries: true,
    canManageTimeTracking: true,
    // 💼 PROJECT MANAGER SPECIFIC - FULL PROJECT CONTROL
    canCreateProjects: true,
    canEditProjects: true,
    canDeleteProjects: true,           // 🔥 ADDED: Full project deletion control
    canArchiveProjects: true,          // 🔥 ADDED: Project archiving control
    canCloneProjects: true,            // 🔥 ADDED: Project cloning capability
    canManageProjectSettings: true,
    canManageProjectTeam: true,
    canAssignProjectManagers: true,    // 🔥 ADDED: Assign other PMs to projects
    canInviteToProject: true,
    canRemoveFromProject: true,
    canAccessProjectFiles: true,       // 🔥 ADDED: Full file access in projects
    canViewProjectBudget: true,
    canManageProjectBudget: true,
    canAccessProjectChat: true,        // 🔥 ADDED: Project communication access
    canCreateProjectAnnouncements: true,
    canModerateProjectDiscussion: true,
    canBulkEditTasks: true,
    canBulkAssignTasks: true,
    canImportTasks: true,
    canExportTasks: true,
    canCreateReports: true,
    canScheduleReports: true,          // 🔥 ADDED: Report scheduling capability
    canCustomizeReports: true,
    canExportReports: true,
    canShareReports: true,
    canCreateDashboards: true,
    canManageDashboards: true,         // 🔥 ADDED: Dashboard management
    canViewProjectAnalytics: true,
    canViewProjectReports: true,
    canExportProjectData: true,
    // Team management within projects
    canCreateTeams: true,              // 🔥 ADDED: Create project teams
    canEditTeams: true,                // 🔥 ADDED: Edit project teams
    canAddMembers: true,               // 🔥 ADDED: Add team members
    canRemoveMembers: true,            // 🔥 ADDED: Remove team members
    canInviteMembers: true,            // 🔥 ADDED: Invite members to projects
    canManageTeamRoles: true,          // 🔥 ADDED: Manage roles within project teams
    canAssignTeamLeads: true,          // 🔥 ADDED: Assign team leads for project teams
    // Communication and collaboration
    canCreateChannels: true,           // 🔥 ADDED: Create project channels
    canManageChannels: true,           // 🔥 ADDED: Manage project channels
    canArchiveChannels: true,          // 🔥 ADDED: Archive project channels
    canModerateChat: true,             // 🔥 ADDED: Moderate project chat
    canDeleteMessages: true,           // 🔥 ADDED: Delete inappropriate messages
    canPinMessages: true,              // 🔥 ADDED: Pin important messages
    canManageChannelPermissions: true, // 🔥 ADDED: Manage channel permissions
    canStartVideoCall: true,           // 🔥 ADDED: Start project video calls
    canShareScreen: true,              // 🔥 ADDED: Screen sharing in meetings
    canRecordMeetings: true,           // 🔥 ADDED: Record project meetings
    canScheduleMeetings: true,         // 🔥 ADDED: Schedule project meetings
    role: "project-manager",
  },

  // ===== WORKSPACE VIEWER (Level 5) =====
  "workspace-viewer": {
    ...BASE_PERMISSIONS,
    // Basic workspace viewing
    canViewWorkspace: true,
    canViewAllUsers: true,
    canViewWorkspaceAnalytics: true,
    canExportWorkspaceData: true,
    canCreateWorkspaceReports: true,
    canViewAuditLogs: true,
    // Project viewing
    canViewAllProjects: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewProjectAnalytics: true,
    canViewProjectReports: true,
    canExportProjectData: true,
    // Basic interaction
    canViewTasks: true,
    canCommentOnTasks: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canDownloadFiles: true,
    canShareFiles: true,
    canViewCalendar: true,
    canAccessKnowledgeBase: true,
    canViewAnalytics: true,
    role: "workspace-viewer",
  },

  // ===== DEPARTMENT HEAD (Level 6) =====
  "department-head": {
    ...BASE_PERMISSIONS,
    // Full project manager capabilities
    canViewWorkspace: true,
    canViewAllProjects: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canViewTasks: true,
    canCreateTasks: true,
    canEditTasks: true,
    canDeleteTasks: true,
    canCommentOnTasks: true,
    canLogTimeOnTasks: true,
    canTrackTime: true,
    canViewTeamMembers: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canReactToMessages: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canUploadFiles: true,
    canDownloadFiles: true,
    canShareFiles: true,
    canViewCalendar: true,
    canAccessKnowledgeBase: true,
    canAssignTasks: true,
    canReassignTasks: true,
    canAssignTasksToMembers: true,
    canCreateSubtasks: true,
    canEditSubtasks: true,
    canDeleteSubtasks: true,
    canAssignSubtasks: true,
    canManageSubtaskHierarchy: true,
    canSetTaskPriority: true,
    canSetTaskDeadlines: true,
    canSetTaskStatus: true,
    canAddTaskLabels: true,
    canViewTeamProgress: true,
    canManageTeamCapacity: true,
    canMentorMembers: true,
    canViewAnalytics: true,
    canViewTeamAnalytics: true,
    canViewPersonalAnalytics: true,
    canViewTimeReports: true,
    canCreateProjects: true,
    canEditProjects: true,
    canDeleteProjects: true,
    canArchiveProjects: true,
    canCloneProjects: true,
    canManageProjectSettings: true,
    canManageProjectTeam: true,
    canAssignProjectManagers: true,
    canInviteToProject: true,
    canRemoveFromProject: true,
    canViewProjectBudget: true,
    canManageProjectBudget: true,
    canCreateProjectAnnouncements: true,
    canModerateProjectDiscussion: true,
    canBulkEditTasks: true,
    canBulkAssignTasks: true,
    canImportTasks: true,
    canExportTasks: true,
    canCreateReports: true,
    canCustomizeReports: true,
    canExportReports: true,
    canShareReports: true,
    canCreateDashboards: true,
    canViewProjectAnalytics: true,
    canViewProjectReports: true,
    canExportProjectData: true,
    // Department head specific permissions
    canInviteUsers: true,
    canManageRoles: true,
    canViewAllUsers: true,
    canViewWorkspaceAnalytics: true,
    canCreateWorkspaceReports: true,
    canAccessAdvancedAnalytics: true,
    canCreateCustomMetrics: true,
    role: "department-head",
  },

  // ===== WORKSPACE MANAGER (Level 7) =====
  "workspace-manager": {
    ...BASE_PERMISSIONS,
    // Full access to everything
    canManageWorkspace: true,
    canViewWorkspace: true,
    canDeleteWorkspace: true,
    canManageWorkspaceSettings: true,
    canManageBilling: true,
    canViewBillingHistory: true,
    canChangePlan: true,
    canInviteUsers: true,
    canRemoveUsers: true,
    canManageRoles: true,
    canAssignDepartmentHeads: true,
    canViewAllUsers: true,
    canViewWorkspaceAnalytics: true,
    canExportWorkspaceData: true,
    canCreateWorkspaceReports: true,
    canScheduleReports: true,
    canManageIntegrations: true,
    canAccessWorkspaceAPI: true,
    canManageWorkspaceSecurity: true,
    canViewAuditLogs: true,
    canManageBackups: true,
    canCreateProjects: true,
    canEditProjects: true,
    canDeleteProjects: true,
    canArchiveProjects: true,
    canCloneProjects: true,
    canManageProjectSettings: true,
    canManageProjectTeam: true,
    canAssignProjectManagers: true,
    canInviteToProject: true,
    canRemoveFromProject: true,
    canViewAllProjects: true,
    canViewAssignedProjects: true,
    canViewProjectDetails: true,
    canAccessProjectFiles: true,
    canViewProjectAnalytics: true,
    canViewProjectReports: true,
    canExportProjectData: true,
    canViewProjectBudget: true,
    canManageProjectBudget: true,
    canAccessProjectChat: true,
    canCreateProjectAnnouncements: true,
    canModerateProjectDiscussion: true,
    canCreateTasks: true,
    canEditTasks: true,
    canDeleteTasks: true,
    canViewTasks: true,
    canViewAllTasks: true,
    canAssignTasks: true,
    canReassignTasks: true,
    canAssignTasksToMembers: true,
    canUnassignTasks: true,
    canCreateSubtasks: true,
    canEditSubtasks: true,
    canDeleteSubtasks: true,
    canAssignSubtasks: true,
    canManageSubtaskHierarchy: true,
    canSetTaskPriority: true,
    canSetTaskDeadlines: true,
    canSetTaskStatus: true,
    canAddTaskLabels: true,
    canManageTaskDependencies: true,
    canCommentOnTasks: true,
    canMentionUsersInTasks: true,
    canAttachFilesToTasks: true,
    canLogTimeOnTasks: true,
    canBulkEditTasks: true,
    canBulkAssignTasks: true,
    canImportTasks: true,
    canExportTasks: true,
    canCreateTeams: true,
    canEditTeams: true,
    canDeleteTeams: true,
    canArchiveTeams: true,
    canAddMembers: true,
    canRemoveMembers: true,
    canInviteMembers: true,
    canManageTeamRoles: true,
    canViewTeamMembers: true,
    canAssignTeamLeads: true,
    canMentorMembers: true,
    canViewTeamProgress: true,
    canManageTeamCapacity: true,
    canCreateTeamChannels: true,
    canManageTeamChannels: true,
    canModerateTeamChat: true,
    canCreateTeamAnnouncements: true,
    canSendMessages: true,
    canSendDirectMessages: true,
    canMentionUsers: true,
    canReactToMessages: true,
    canCreateChannels: true,
    canJoinChannels: true,
    canLeaveChannels: true,
    canManageChannels: true,
    canArchiveChannels: true,
    canModerateChat: true,
    canDeleteMessages: true,
    canPinMessages: true,
    canManageChannelPermissions: true,
    canStartVideoCall: true,
    canShareScreen: true,
    canRecordMeetings: true,
    canScheduleMeetings: true,
    canUploadFiles: true,
    canDownloadFiles: true,
    canDeleteFiles: true,
    canOrganizeFiles: true,
    canShareFiles: true,
    canManageFileVersions: true,
    canViewCalendar: true,
    canCreateEvents: true,
    canEditEvents: true,
    canDeleteEvents: true,
    canManageAvailability: true,
    canBookResources: true,
    canManageTimeOff: true,
    canTrackTime: true,
    canViewTimeTracking: true,
    canEditTimeEntries: true,
    canApproveTimeEntries: true,
    canManageTimeTracking: true,
    canAccessKnowledgeBase: true,
    canCreateDocuments: true,
    canEditDocuments: true,
    canDeleteDocuments: true,
    canManageDocumentPermissions: true,
    canViewAnalytics: true,
    canViewPersonalAnalytics: true,
    canViewTeamAnalytics: true,
    canViewTeamPerformance: true,
    canViewIndividualPerformance: true,
    canViewProductivityMetrics: true,
    canViewBudgetAnalytics: true,
    canViewTimeReports: true,
    canCreateReports: true,
    canCustomizeReports: true,
    canExportReports: true,
    canShareReports: true,
    canAccessAdvancedAnalytics: true,
    canCreateDashboards: true,
    canCreateCustomMetrics: true,
    canAccessSystemSettings: true,
    canManageSystemIntegrations: true,
    canManageAPIAccess: true,
    canViewSystemHealth: true,
    canManageSystemBackups: true,
    canManageSecurity: true,
    canViewSecurityLogs: true,
    canManageSSO: true,
    canManage2FA: true,
    canManageDataRetention: true,
    canAccessAuditLogs: true,
    canManageCompliance: true,
    canExportAuditData: true,
    canManageDataGovernance: true,
    canAccessBetaFeatures: true,
    canUseAI: true,
    canManageAISettings: true,
    canAccessDeveloperTools: true,
    role: "workspace-manager",
  },
};

/**
 * Check if one role is higher than another in hierarchy
 */
export function isRoleHigher(role1: UserRole, role2: UserRole): boolean {
  return ROLE_HIERARCHY[role1] > ROLE_HIERARCHY[role2];
}

/**
 * Check if a role has minimum level access
 */
export function hasMinimumRole(userRole: UserRole, requiredRole: UserRole): boolean {
  return ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[requiredRole];
}

/**
 * Get permissions for a specific role
 */
export function getRolePermissions(role: UserRole): AllPermissions {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS["guest"];
}

/**
 * Check if a role has a specific permission
 */
export function hasPermission(
  role: UserRole, 
  permission: keyof AllPermissions
): boolean {
  const rolePermissions = getRolePermissions(role);
  return rolePermissions[permission] === true;
} 