import { HTTPException } from "hono/http-exception";
import { getDatabase } from "../../database/connection";
import { workspaceTable, userTable, roleAssignmentTable, workspaceUserTable } from "../../database/schema";
import { publishEvent } from "../../events";
import { eq } from "drizzle-orm";
import { createId } from "@paralleldrive/cuid2";
import logger from '../../utils/logger';

async function createWorkspace(name: string, ownerEmail: string) {
  const db = getDatabase();

  // Check if the user exists in the database
  const [existingUser] = await db
    .select()
    .from(userTable)
    .where(eq(userTable.email, ownerEmail))
    .limit(1);

  if (!existingUser) {
    throw new HTTPException(400, {
      message: "User not found. Please ensure you are logged in correctly.",
    });
  }

  const [workspace] = await db
    .insert(workspaceTable)
    .values({
      name,
      ownerId: existingUser.id,
    })
    .returning();

  if (!workspace) {
    throw new HTTPException(500, {
      message: "Failed to create workspace",
    });
  }

  // 🏆 SECURITY: Assign workspace-manager (owner) role to creator
  try {
    const ownerAssignmentId = createId();
    await db.insert(roleAssignmentTable).values({
      id: ownerAssignmentId,
      userId: existingUser.id,
      role: "workspace-manager",
      workspaceId: workspace.id,
      isActive: true,
      // assignedAt will be auto-generated by defaultNow()
      // Note: assignedBy, reason, notes, createdAt, updatedAt don't exist in schema
    });

    // TODO: Record in role history when roleHistoryTable is created
    // Role history table doesn't exist in schema yet

    logger.debug(`🏆 Assigned workspace-manager role to workspace creator: ${ownerEmail} for workspace ${workspace.id}`);
  } catch (error) {
    logger.error("Failed to assign owner role:", error);
    // Continue - workspace is created, role assignment failure shouldn't block
  }

  // 👥 Add owner as a member of the workspace
  try {
    const membershipId = createId();
    await db.insert(workspaceUserTable).values({
      id: membershipId,
      workspaceId: workspace.id,
      userId: existingUser.id,
      userEmail: ownerEmail,
      role: "admin",
      status: "active",
      // joinedAt will be auto-generated by now()
    });

    logger.debug(`👥 Added workspace creator as member: ${ownerEmail} for workspace ${workspace.id}`);
  } catch (error) {
    logger.error("Failed to add owner as workspace member:", error);
    // Continue - workspace is created, membership failure shouldn't block
  }

  publishEvent("workspace.created", {
    workspaceId: workspace.id,
    ownerEmail,
  });

  return workspace;
}

export default createWorkspace;

